services:
  # Opengist 
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    ports:
      - "6157:6157" # HTTP port
      - "2222:2222" # SSH port, can be removed if you don't use SSH
    volumes:
      - $DOCKER_PATH/opengist:/opengist
    environment:
      CONFIG: |
        log-level: info
        ssh.git-enabled: false
        disable-signup: false # You may wish to change this to true after you sign up the first time. 

  # Glances - system monitoring
  glances:
    container_name: glances
    ports:
      - 61208-61209:61208-61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GLANCES_OPT=-w
    restart: always
    pid: host
    image: nicolargo/glances

  # Ntfy
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=$TZ    # optional: set desired timezone
    user: $PUID:$PGID # optional: replace with your own user/group or uid/gid
    volumes:
      - $DOCKER_PATH/ntfy/cache:/var/cache/ntfy
      - $DOCKER_PATH/ntfy:/etc/ntfy
    ports:
      - 8585:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

  # Homepage dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3344:3000
    volumes:
      - $DOCKER_PATH/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - $DOCKER_PATH/homepage/images:/app/public/images
      - $DOCKER_PATH/homepage/icons:/app/public/icons
    environment:
      PUID: $PUID
      PGID: $PGID
    restart: unless-stopped

  # link manager
  linkding:
    image: sissbruecker/linkding
    container_name: linkding
    ports:
      - 9999:9090
    volumes:
      - $DOCKER_PATH/linkding:/etc/linkding/data
    restart: unless-stopped

  # White Board Online
  wbo:
    image: lovasoa/wbo
    container_name: wbo
    ports:
      - 5005:80
    volumes:
      - $DOCKER_PATH/wbo:/opt/app/server-data" 
    restart: unless-stopped

  # file browser - web-based file browser/manager
  filebrowser:
    container_name: filebrowser
    volumes:
      - $MEDIA_PATH:/srv
      - $DOCKER_PATH/filebrowser/filebrowser.db:/database/filebrowser.db
      - $DOCKER_PATH/filebrowser/.filebrowser.json:/.filebrowser.json
    environment:
      user: "$PUID:$PGID"
    ports:
      - 6543:80
    image: filebrowser/filebrowser

  # Joplin
  joplin:
    container_name: joplin
    image: joplin/server:latest
    depends_on:
        - joplindb
    ports:
        - "2230:2230"
    restart: unless-stopped
    environment:
        - APP_PORT=2230
        - APP_BASE_URL=http://joplin.$DOMAIN
        - DB_CLIENT=pg
        - POSTGRES_PASSWORD=joplinpsw
        - POSTGRES_DATABASE=joplin
        - POSTGRES_USER=joplinuser
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=joplindb

  joplindb:
    container_name: joplindb
    image: postgres:13.1
    volumes:
        - $DOCKER_PATH/joplindb:/var/lib/postgresql/data
  #  ports:
   #     - "5435:5432"
    restart: unless-stopped
    environment:
        - POSTGRES_PASSWORD=joplinpsw
        - POSTGRES_USER=joplinuser
        - POSTGRES_DB=joplin

  # Mealie
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      TZ: $TZ
    volumes:
      - $DOCKER_PATH/mealie/data/:/app/data
    labels: 
      autoheal: true

  # Vaultwarden Password Manager
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: always
    volumes:
      - $DOCKER_PATH/vaultwarden/data:/data
      - $DOCKER_PATH/vaultwarden/ssl:/ssl
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8089:8089
      - 3012:3012
    user: $PUID:$PGID
    environment:
      - LOG_FILE=/data/vaultwarden.log
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      #- SIGNUPS_ALLOWED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
      - DOMAIN=https://vw.$DOMAIN
      - ROCKET_PORT=8089
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=$VW_TOKEN
      - SMTP_HOST=$GM_SERVER
      - SMTP_FROM=$GM_USER
      - SMTP_PORT=$GM_PORT
      - SMTP_SSL=true
      - SMTP_USERNAME=$GM_USER
      - SMTP_PASSWORD=$GM_PSW

  # Syncthing
  syncthing: 
    container_name: syncthing
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
    volumes:
      - $DOCKER_PATH/syncthing/config:/config
      - $DOCKER_PATH/syncthing/data1:/data1
      - $DOCKER_PATH/syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    image: linuxserver/syncthing
    restart: unless-stopped

  # hasty paste
  hastypaste:
    container_name: hastypaste
    image: ghcr.io/enchant97/hasty-paste:1
    restart: unless-stopped
    environment:
      NEW_AT_INDEX: "true"
      DEFAULT_USE_LONG_ID: "false"
      ENABLE_PUBLIC_LIST: "true"
    volumes:
      - $DOCKER_PATH/hastypaste:/app/data
    ports:
      - 8069:8000

  # SearNGX
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - external
    ports:
     - "5080:8080"
    volumes:
      - $DOCKER_PATH/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://sear.$DOMAIN/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  # Languagetool - self-host spell checker
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
        - 8018:8010  # Using default port from the image
    labels:
      autoheal: 'true'
    networks:
      - external
    environment:
        - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
        - Java_Xms=256m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
        - Java_Xmx=512m  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
        - $DOCKER_PATH/languagetool:/ngrams
    restart: unless-stopped
    healthcheck:
      test: curl -d "text=Color atomize" -d "language=en-AU" http://localhost:8010/v2/check > /dev/null || exit 1
      start_period: 25s
      timeout: 5s
      interval: 10s
      retries: 3

# UptimeKuma service monitor
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    ports:
      - 2001:3001
    volumes:
      - $PERSIST/uptimekuma:/app/data
    dns:
      - 192.168.1.2
